# Chap04 예외
4장에서는 `JdbcTemplate`을 대표료 하는 스프링의 데이터 엑세스 기능에 담겨 있는 예외처리와 관련된 접근 방법에 대해 알아본다. 이를 통해 예외를 처리하는 베스트 프렉티스도 살펴본다. 

# 4.1 사라진 SQLException
`JdbcContext`로 만들었던 코드를 스프링의 `JdbcTemplate`으로 바꾸면서 SQLException이 사라졌다. 이 SQLException은 어디로 간 것일까?

## 4.1.1 초난감 예외처리
SQLException이 어떻게 사라졌는지 알아보기 전에 먼저 코드에 종종 발견되는 초난감 예외처리들을 살펴보자. 

### 예외 블랙홀
``` java
try {

} catch (SQLException e) {
}
```
이 코드에서는 예외를 잡고 아무것도 하지 않는다. 이는 원치 않는 예외가 발생하는 것보다도 훨씬 더 나쁜 일이다. 그 시스템 오류나 결과의 원인이 무엇인지 찾아내기가 매우 힘들다.
``` java
} catch (SQLException e) {
    System.out.println(e);
}
```
``` java
} catch (SQLException e) {
    e.printStackTrace();
}
```
위 코드도 안좋은 예시다. 콘솔에 뜬다고 해도 다른 로그나 메시지에 금방 묻혀버리면 놓치게 된다. 운영서버에 올라가면 더 심각하다. 이는 화면에 메시지를 출력한 것이지 예외를 처리한 게 아니다.  
예외 처리할 때 반드시 지켜야할 핵심 원칙은 한 가지다. **모든 예외는 적절하게 복구되든지 아니면 작업을 중단시키고 운영자 또는 개발자에게 분명하게 통보돼야 한다.** 
SQLException이 발생한 이유는 SQL 문법에 에러가 있거나 DB에서 처리할 수 없을 정ㄷ로 데이터 엑세스 로직에 심각한 버그가 있거나, 서버가 죽거나 네트워크가 끊기는 등의 심각한 상황이 벌어졌기 때문이다. 굳이 예외를 잡아서 뭔가 조치를 취할 방법이 없다면 잡지를 말아야 한다. 메소드에 throws SQLException을 선언해서 메소드 밖으로 던지고 자신을 호출한 코드에 예외처리 책임을 전가해라.

### 무의미하고 무책임한 throws
catch 블록으로 예외를 잡아봐야 해결할 방법도 없고 각종 이름도 긴예외들을 처리하는 코드를 매번 throws로 선언하기 귀찮아지기도 시작하면 아래와 같이 메소드 선언에 throws Exception을 기계적으로 붙이는 개발자도 있다. 
``` java
public void method1() throws Exception {
    method2();
}

public void method2() throws Exception {
    method3();
}

public void method3() throws Exception {
    ...
}
```
이런 무책임한 throws 선언도 문제점이 있다. 자신이 사용하려는 메소드에 throws Excpetion이 있다고 생각해 보자. 그런 메소드 선언에서는 의미 있는 정보를 얻을 수 없다. 절말 무엇인가 실행중에 예외적인 상황이 발생할 수 있다는 것인지, 아니면 그냥 습관적으로 복사해서 붙여 놓은 것인지 알 수가 없다. 

## 4.1.2 예외의 종류와 특징
**체크 예외(Checked Excpetion)**이라고 불리는 명시적인 처리가 필요한 예외를 사용하고 다루는 방법은 자바 개발자들 사이에서 오랫동안 많은 논쟁이 있었다.  
자바에서 throw를 통해 발생시킬 수 있는 예외는 크게 세 가지가 있다. 
1. Error  
`java.lang.Error`클래스의 서브클래스들이다. 에러는 시스템에 뭔가 비정상적인 상황이 발생했을 경우에 사용된다. 그래서 주로 자바 VM에서 발생시키는 것이고 애플리케이션 코드에서 잡으려고 하면 안 된다. `OutOfMemoryError`나 `ThreadDeath`같은 에러는 catch블록으로 잡아봤자 아무런 대응 방법이 없기 때문이다.

2. Exception과 체크 예외  
`java.lang.Exception`클래스와 그 서브클래스로 정의되는 예외들은 개발자들이 만든 애플리케이션 코드의 작업 중에 예외 상황이 발생했을 경우에 사용된다. 
* `체크 예외`: Exception클래스의 서브클래스 이면서 RuntimeException 클래스를 상속하지 않은 것들
* `언체크 예외(Unchecked exception)`: RumtimeException을 상속한 클래스  
일반적으로 예외라 하면 체크 예외라고 생각해도 된다. **체크 예외가 발생할 수 있는 메소드를 사용할 경우 반드시 예외를 처리하는 코드를 함께 작성해야 한다.** 그렇지 않으면 컴파일에러가 발생한다. 

3. RuntimeException과 언체크/런타임 예외
`java.lang.RuntimeException` 클래스를 상속한 예외들은 명시적인 예외처리를 강제하기 않기 때문에 언체크 예외라고 불린다. 또는 대표 클래스 이름을 따서 `런타임 예외` 라고도 한다. 이 런타임 예외는 catch문으로 잡거나 throws로 선언하지 않아도 된다. 명시적으로 해도 상관없다.  
**런타임 예외는 주로 프로그램의 오류가 있을 때 발생하도록 의도된 것들이다.** 대표적으로 NullPointerException이나, IllegalArgumentException등이 있다. 이런 예외는 코드에서 미리 조건을 체크하도록 주의 깊게 만든다면 피할 수 있다. 피할 수 있지만 개발자가 부주의해서 발생할 수 있는 경우에 발생하도록 만든 것이 런타임 예외다.

## 4.1.3 예외처리 방법
### 예외 복구
예외상황을 포악하고 문제를 해결해서 정상 상태로 돌려놓자.

### 예외 처리 회피
예외처리를 자신이 담당하지 않고 자신을 호출한 쪽으로 던져버릴 수도 있다. throws 문으로 선언해서 예외가 발생하면 알아서 던져지게 하거나 catch 문으로 일단 예외를 잡은 후에 로그를 남기고 다시 예외를 던지는 것이다.  
콜백과 템플릿 처럼 긴밀하게 역할을 분담하고 있는 관계가 아니라면 자신의 코드에서 발생하는 예외를 그냥 던져버리는건 무책임한 책임회피일 수 있다. **에외를 회피하는 것은 예외를 복구하는 것처럼 의도가 분명해야 한다.**

### 예외 전환
예외 전환은 발생한 예외를 그대로 넘기는 게 아니라 적절한 예외로 전환해서 던진다는 특징이 있다.  
예외 전환은 보통 두 가지 목적으로 사용된다. 
1. 의미를 분명하게 해 줄 수 있는 예외로 바꿔주기 위해서  
보통 전환하는 예외에 원래 발생한 예외를 담아서 중첩 예외로 만드는 것이 좋다.
2. 예외를 처리하기 쉽고 단순하게 만들기 위해 포장  
주로 예외처리를 강제하는 체크 예외를 런체크 예외인 런타임 예외로 바꾸는 경우에 사용

일반 적으로 체크 예외를 계속 throws를 사용해 넘기는 건 무의미하다. 메소드 선언은 지저분해지고 아무런 장점이 없다. 어차피 복구하지 못할 예외라면 애플리케이션 코드에서는 런타임 예외로 포장해서 던져버리고, 예외처리 서비스 등을 이용해 자세한 로그를 남기는 등으로 처리하는게 바람직하다. 

## 4.1.4 예외처리 전략
지금까지 살펴본 예외의 종류와 처리 방법 등을 기준으로 일관된 예외처리 전략을 정리해보자. 

### 런타임 예외의 보편화
서버 환경에서는 체크 예외의 활용도와 가치는 점점 떨어지고 있따. 자칫하면 throws Exception으로 점철된 아무런 의미없는 메소드들을 낳을 뿐이다. 그래서 대응이 불가능한 체크 예외라면 빨리 런타임 예외로 전환해서 던지는게 낫다.  
최근에 등장하는 표준 스펙 또는 오픈소스 프레임워크에서는 API가 발생시키는 예외를 체크 예외 대신 언체크 예외로 정의하는 것이 일반화되고 있다. 언체크 예외라도 필요하면 얼마든지 catch 블록으로 잡아서 복구하거나 처리할 수 있다.

### add() 메소드의 예외처리
``` java
public void add(User user) throws DuplicatedUserIdException, SQLException {
    try {
        ...
    } catch (SQLException e) {
        if (e.getErrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY)
            throw DuplicatedUserIdException();
        else
            throw e;
    }
}
```
`add()` 메소드에서 동일한 id가 존재할 시 발생하는 `DuplicatedUserIdException`과 `SQLException` 두 가지의 체크 예외를 던지게 되어 있다.  
`DuplicatedUserIdException`를 굳이 체키 예외로 둬야 하는 것은 이니다. 잡아서 처리할 수 있다면 굳이 체크 예외로 만들지 않고 런타임 예외로 만드는 게 낫다. 대신 `add()`메소드는 명시적으로 `DuplicatedUserIdException`를 던진다고 선언해야 한다. 그래야 의미있는 정보를 전달해 줄 수 있다. 이를 사용해 `add()`를 수정해보자. 
``` java
public class DuplicatedUserIdException extends RuntimeException {
    public DuplicatedUserIdException(Throwable cause) {
        super(cause);
    }
}
```
`DuplicatedUserIdException`는 `RuntimeException`를 상속해 런타임 예외로 만든다. 
``` java
public void add(User user) throws DuplicatedUserIdException {
    try {
        ...
    } catch (SQLException e) {
        if (e.getErrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY)
            throw DuplicatedUserIdException(); // 예외 전환
        else
            throw new RumtimeException(); // 예외 포장
    }
}
```
원래는 `SQLException`를 직접 던지도록 했는데, 이제는 런타임 예외로 전환해서 던지도록 한다. 이제는 언체크 예외가 되어 메소드 선언의 throws에 포함시킬 필요가 없다. 

### 애플리케이션 예외
 시스템 또는 외부의 예외상황이 원인이 아니라 애플리케이션 자체의 로직에 의해 의도적으로 발생시키고, 반드시 catch 해서 무엇인가 조치를 취하도록 요구하는 예외

## 4.1.5 SQLException은 어떻게 됐나? 
`SQLException`은 코드 레벨에서는 복구할 방법이 없다. 띠라서 언체크/런타임 예외로 전환해주는 예외처리 전략을 활용해야한다.
스프링의 `jdbcTemplate`은 바로 이 예외전략을 따르고 있다. `jdbcTemplate` 템플릿과 콜백안에서 발생하는 모든 `SQLException`은 런타임 예외인 `DataAccessException`으로 포장해서 던져준다. 그래서 DAO 메소드에서 `SQLException`이 모두 사라진 것이다.   
그 밖에도 스프링 API메소드에 정의되어 있는 대부분의 예외는 런타임 예외다. 즉, 발생 가능한 예외가 있다고 하더라도 이를 처리하도록 강제하지 않는다.